services:
  postgres:
    image: postgres:17-alpine
    container_name: nexobank-postgres
    environment:
      POSTGRES_DB: nexobank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nexobank"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: nexobank-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://postgres:5432/nexobank
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: nexobank-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:
