spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}

app.security.refresh-cookie.secure=${REFRESH_COOKIE_SECURE:true}
